apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messager

labels:
  - pairs:
      app.kubernetes.io/part-of: messager
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-init-configmap.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - minio-secret.yaml
  - csi-s3-secret.yaml
  - minio.yaml
  - message-uploads-pvc.yaml
  - minio-bucket-job.yaml
  - migrate-users-job.yaml
  - migrate-messages-job.yaml
  - user-service.yaml
  - message-service.yaml
  - bff.yaml
  - frontend.yaml
  - ingress.yaml

configMapGenerator:
  - name: users-migrations-cm
    files:
      - migrations/users/001_init.sql
  - name: messages-migrations-cm
    files:
      - migrations/messages/001_init.sql
      - migrations/messages/002_add_file_name.sql

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: mablinov2704/frontend
    newName: mablinov2704/frontend
    newTag: latest
  - name: mablinov2704/bff
    newName: mablinov2704/bff
    newTag: latest
  - name: mablinov2704/user-service
    newName: mablinov2704/user-service
    newTag: latest
  - name: mablinov2704/message-service
    newName: mablinov2704/message-service
    newTag: latest
