apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "CHANGEME_DB_USER"
  POSTGRES_PASSWORD: "CHANGEME_DB_PASSWORD"
  USER_DB_DSN: "host=postgres user=CHANGEME_DB_USER password=CHANGEME_DB_PASSWORD dbname=messager_users sslmode=disable"
  MSG_DB_DSN: "host=postgres user=CHANGEME_DB_USER password=CHANGEME_DB_PASSWORD dbname=messager_messages sslmode=disable"
