apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messager-dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
    includeSelectors: false

patches:
  - path: patches/ingress-host.yaml
  - path: patches/frontend-service.yaml
  - path: patches/message-service-emptydir.yaml
    target:
      kind: Deployment
      name: message-service
  - path: patches/resources.yaml
  - path: patches/configmap-bucket.yaml
  - path: patches/minio-nodeport.yaml
  - path: patches/message-uploads-pvc.yaml

images:
  - name: mablinov2704/frontend
    newTag: latest
  - name: mablinov2704/bff
    newTag: latest
  - name: mablinov2704/user-service
    newTag: latest
  - name: mablinov2704/message-service
    newTag: latest
